HelpYourCity.API/Controllers/GoalController.cs
using System.Threading.Tasks;
using HelpYourCity.Core.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace HelpYourCity.API.Controllers
{
    [ApiController]
    [Route("api/goals")]
    public class GoalController : ControllerBase
    {
        private readonly IGoalService _goalService;

        public GoalController(IGoalService goalService)
        {
            _goalService = goalService;
        }

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var response = await _goalService.GetPublishedGoals();
            return Ok(response);
        }

        [HttpGet("{slug}")]
        public async Task<IActionResult> GetOne(string slug)
        {
            var response = await _goalService.GetGoalBySlug(slug);
            return Ok(response);
        }
        
        
    }
}

HelpYourCity.API/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - HelpYourCity</title>
    <link rel="stylesheet" href="~/admin/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/admin/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HelpYourCity</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @if (User.Identity.IsAuthenticated)
            {
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Goal" asp-action="Index">Goal</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            }
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - HelpYourCity - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/admin/lib/jquery/dist/jquery.min.js"></script>
<script src="~/admin/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/admin/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>